model:
  num_classes: 10  # Number of classes for classification

training:
  epochs: 20
  batch_size: 32
  learning_rate: 0.001
  validation_split: 0.2
  early_stopping_patience: 5
  save_best_model: true
  model_dir: "models/"
